---
# tasks file for ansible-zsh
- name: Make sure .config/zsh directory exists
  file:
    path: /home/{{user}}/.config/zsh
    state: directory

- name: Copy .zshenv to set ZDOTDIR
  copy:
    src: zshenv
    dest: /home/{{user}}/.zshenv

- name: Copy zsh configuration files
  copy:
    src: "{{item}}"
    dest: /home/{{user}}/.config/zsh/{{item}}
  with_items:
    - zsh_plugins
    - .zshrc
    - functions.zsh
    - aliases.zsh
    - dircolors
  register: zshconfig

- name: Run antibody local install script
  script: install_antibody.sh -b /home/{{user}}/.local/bin
  args:
    creates: /home/{{user}}/.local/bin/antibody

- name: Install zsh plugins
  command: "antibody bundle < /home/{{user}}/.config/zsh/zsh_plugins > /home/{{user}}/.zsh_plugins.sh"
  when: zshconfig.changed

